// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories;

#nullable disable

namespace StoreApp.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20240712091441_startPoint")]
    partial class startPoint
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Price = 100m,
                            ProductName = "Phone"
                        },
                        new
                        {
                            ProductId = 2,
                            Price = 200m,
                            ProductName = "Computer"
                        },
                        new
                        {
                            ProductId = 3,
                            Price = 300m,
                            ProductName = "tablet"
                        },
                        new
                        {
                            ProductId = 4,
                            Price = 400m,
                            ProductName = "kulaklik"
                        },
                        new
                        {
                            ProductId = 5,
                            Price = 500m,
                            ProductName = "sarz"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
